application: dump1090-helper
version: test
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /dump1090
  static_dir: dump1090

- url: /secure/.*
  script: main.app
  login: admin

- url: /static
  static_dir: static
  expiration: 7d
  http_headers:
    X-GAE-Header: dump1090-helper.appspot.com

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest

builtins:
- deferred: on
- appstats: off
- admin_redirect: on

inbound_services:
- warmup
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- xmpp_error

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.fubar
- ^(.*/)?.*/ClientSide/.*